/*
 * Module: clk_wiz_0
 * Description: Clock generation module (placeholder for the Clocking Wizard IP core).
 * In Vivado, this module should be generated by the Clocking Wizard from the IP Catalog
 * to convert the system clock (e.g., 100MHz) to the VGA pixel clock (25.175MHz).
 * This file is for simulation purposes only and is not intended for synthesis.
 */
module clk_wiz_0(
    // Clock in ports
    input      clk_in1,
    // Clock out ports
    output     clk_out1,
    // Status and control signals
    input      reset,
    output     locked
);

    // In simulation, we can simply pass through the clock or divide it.
    // Here we assume the input clock is 100MHz and we need to divide by 4 to get 25MHz.
    reg [1:0] count = 0;
    reg clk_out_reg = 0;

    always @(posedge clk_in1 or posedge reset) begin
        if (reset) begin
            count <= 0;
            clk_out_reg <= 0;
        end else begin
            count <= count + 1;
            if (count == 1) begin
                clk_out_reg <= ~clk_out_reg; // 2分频
            end
        end
    end
    
    // Simple divide-by-4 logic
    assign clk_out1 = clk_out_reg; 

    // Locked signal, can be tied high in simulation
    assign locked = 1'b1;

endmodule